Gemfile
Gemfile.lock
app/assets/javascripts/equipment.coffee
app/assets/stylesheets/equipment.scss
app/assets/stylesheets/scaffolds.scss
app/controllers/equipment_controller.rb
app/helpers/equipment_helper.rb
app/models/capability.rb
app/models/equipment.rb
app/models/equipment_capability.rb
app/models/equipment_material.rb
app/models/lab_space.rb
app/models/material.rb
app/views/equipment/_equipment.json.jbuilder
app/views/equipment/_form.html.erb
app/views/equipment/edit.html.erb
app/views/equipment/index.html.erb
app/views/equipment/index.json.jbuilder
app/views/equipment/new.html.erb
app/views/equipment/show.html.erb
app/views/equipment/show.json.jbuilder
config/routes.rb
db/migrate/20190226060349_create_capabilities.rb
db/migrate/20190226061403_create_materials.rb
db/migrate/20190226062657_create_equipment.rb
db/migrate/20190226065238_create_equipment_materials.rb
db/migrate/20190226072038_create_equipment_capabilities.rb
db/migrate/20190302024338_add_lab_space_to_equipment.rb
db/schema.rb

CRUD Equipment
**New Models**:
- Material
- Capability
- Equipment
[Related Backlog Item](https://github.com/ProyectoIntegrador2018/makers/issues/7)

Add equipment

---

app/controllers/equipment_controller.rb
app/models/equipment.rb
app/views/equipment/index.html.erb
app/views/home/landing.html.erb
app/views/shared/_search.html.erb
config/routes.rb

- Adds search functionality for equipment by name, materials and capabilities
- Adds search form to home and equipment index
- Creates non-nested resource for equipment index

Add search for equipment

---

Gemfile
Gemfile.lock
app/controllers/lab_spaces_controller.rb
app/controllers/labs_controller.rb
app/models/equipment.rb
app/models/lab.rb
app/models/lab_space.rb
app/uploaders/image_uploader.rb
app/views/equipment/_form.html.erb
app/views/equipment/index.html.erb
app/views/equipment/show.html.erb
app/views/lab_spaces/_form.html.erb
app/views/labs/_form.html.erb
config/environment.rb
db/migrate/20190302233607_add_image_to_lab_spaces.rb
db/migrate/20190302233612_add_image_to_labs.rb
db/schema.rb

- Adds carrierwave gem and creates ImageUploader
- Add fields for image to lab and lab spaces
- Update controllers and template views

Add images

---

app/controllers/equipment_controller.rb

Fix update method for materials and capabilities

---

app/controllers/equipment_controller.rb
app/models/available_hour.rb
app/models/equipment.rb
app/models/reservation.rb
app/models/user.rb
db/migrate/20190325023714_create_available_hours.rb
db/migrate/20190325025304_create_reservations.rb
db/migrate/20190327052053_add_technical_description_to_equipment.rb
db/migrate/20190327052754_add_institutional_id_to_users.rb
db/schema.rb

**Crear modelos:**
**Cambios de la junta:**
💩

Add models for Reservation and AvailableHour

---

.rubocop.yml
app/controllers/equipment_controller.rb
app/controllers/reservations_controller.rb
app/helpers/reservations_helper.rb
app/models/reservation.rb
app/views/reservations/_form.html.erb
app/views/reservations/_reservation.json.jbuilder
app/views/reservations/edit.html.erb
app/views/reservations/index.html.erb
app/views/reservations/index.json.jbuilder
app/views/reservations/new.html.erb
app/views/reservations/show.html.erb
app/views/reservations/show.json.jbuilder
config/routes.rb

- Adds CRUD for reservations
- Limits reservations to signed in users
- Allows anyone to access a reservation index only from a nested equipment resource
- Allows to create a reservation only from an equipment nested resource as a signed in user
- Validates presence of fields, date range and date overlaps 
Related Stories: #9 #34

Reservations

---

app/models/reservation.rb

- Fixes bug: wrong validation for overlapped

Fixes bug: overlapped should only be checked for same equipment.

---

app/controllers/application_controller.rb

Fix bug 41: missing allowed user params

---

config/environments/production.rb
config/initializers/devise.rb

- Completes mailer configuration for sign up and recover password
#15 #20

Add configuration for sendgrid

---

app/views/devise/passwords/new.html.erb

Added style to reset password view

---

app/controllers/reservations_controller.rb

Fixes #53 
Typo on method call

Fix bug 53

---

Gemfile
app/assets/javascripts/application.js
app/assets/stylesheets/_base.scss
app/assets/stylesheets/_calendar.scss
app/assets/stylesheets/application.css.scss
app/views/equipment/show.html.erb
config/locales/es.yml

This PR:
- Adds the front-end functionality for the user to cancel his/her own resrevations
- Removes turbolinks definitively (useless and does not properly load javascript)
- is missing back-end cancellation 
- Partially fixes #34

Add ability to cancel a reservation

---

.reek.yml
app/models/available_hour.rb
app/models/reservation.rb

Fixes 1 code smell from code climate 👃 ☁️ 
- refactor la validación de _"ver si la reservación que hace un usuario esta dentro del horario disponible del  equipo"_

Refactor date_is_available in Reservation Model

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_home.scss
app/controllers/equipment_controller.rb
app/controllers/labs_controller.rb
app/dashboards/lab_dashboard.rb
app/dashboards/lab_space_dashboard.rb
app/views/admin/equipment/show.html.erb
app/views/equipment/_equipment.json.jbuilder
app/views/equipment/show.html.erb
app/views/labs/show.html.erb

This PR:
- Fixes routing/link bugs
- Adds carrierwave integration for admin upload
- Adds saving of schedule
- Bug:
```
NoMethodError (undefined method `permit' for #<Array:0x00007fbfd4016a30>):
app/controllers/equipment_controller.rb:115:in `schedule_params'
```
when saving schedule

Add save schedule. Save lab space and equipment admin

---

app/controllers/registrations_controller.rb
app/views/devise/sessions/new.html.erb
app/views/home/landing.html.erb
app/views/layouts/application.html.erb
config/locales/es.yml
config/routes.rb

- Overrides redirect after sign up, now redirects to sign in page to show confirmation flash.
- Discards all flashes after rendering every view.

Only display flashes in registrations pages, discard otherwise

---

app/controllers/equipment_controller.rb
app/views/labs/show.html.erb
db/seeds.rb

This PR:
- Specifies the TZ when adding available hours
- Adds the time zone to the seeds
- Fixes a bug in equipment_controller

Fix reservation bug

---

app/controllers/home_controller.rb
app/dashboards/lab_administration_dashboard.rb
app/dashboards/user_dashboard.rb
app/views/home/profile.html.erb

Profile:
- Refactors profile action, prefer queries in controller instead of view
- Refactors Matrícula/Nómina display
Admin Dashboards:
- Give options for user `role` field on `UserDashboard`
- Scopes options for `LabAdministration :admin` to only admins and lab_admins on `LabAdministrationDashboard`

Refactor profile action

---

app/assets/stylesheets/admin.css.scss
app/policies/admin_policy.rb
app/views/admin/labs/_form.html.erb
app/views/admin/labs/new.html.erb
app/views/labs/index.html.erb

- Added styles to the Lab Form
- Removed the "New Lab" button from external site (admin will only be able to create new labs from the dashboard"

New Lab Form in Admin Dashboard

---

.gitignore
app/assets/stylesheets/admin.css.scss
app/dashboards/equipment_dashboard.rb
app/fields/belongs_to_with_user_field.rb
app/views/admin/equipment/_form.html.erb
app/views/admin/equipment/new.html.erb
app/views/equipment/show.html.erb
app/views/labs/show.html.erb

- Fixes client's request
- Adds a more intuitive way of adding/editing available hours
- Makes sure we always respect the correct time zone everywhere
- Makes the client happier
Fixes most of #79

Refactor available hours in admin dashboard

---

Gemfile
Gemfile.lock
app/controllers/reservations_controller.rb
app/dashboards/reservation_dashboard.rb
app/models/reservation.rb
app/policies/equipment_policy.rb
app/policies/role_policy.rb
app/views/admin/equipment/_form.html.erb
app/views/equipment/show.html.erb
app/views/lab_spaces/show.html.erb
app/views/labs/show.html.erb
config/application.rb
db/seeds.rb
spec/models/reservation_spec.rb

- last min fixes 🐛  😭 
- small enhancements in admin dashboard
Fixes: #10 and other issues related to time zones

Fix issues

---

app/controllers/admin/equipment_controller.rb
app/controllers/equipment_controller.rb
app/models/equipment.rb
app/views/lab_spaces/show.html.erb

- Fix adding new materials and capabilities on dashboard
- Update lab_space show to new materials/capabilities flow

Fix adding new materials and capabilities 

---

Dockerfile
Gemfile
Gemfile.lock
bin/dev-entrypoint
docker-compose.yml

Changes docker related files to make docker-compose work correctly.

Dockerize project correctly

---

Gemfile
Gemfile.lock
app/controllers/lab_spaces_controller.rb
app/controllers/labs_controller.rb
app/models/lab.rb
app/models/lab_space.rb
app/models/user.rb
app/policies/lab_space_policy.rb
app/policies/managed_models_policy.rb
app/views/labs/index.html.erb
app/views/shared/_nav.html.erb
db/migrate/20190913184336_add_admin_to_labs.rb
db/schema.rb

Change permissions for normal users, Super admin, Lab admin and space admin
Permissions were changes mainly for creating, updating, deleting and seeing labs, spaces, and equipment.

Correct permissions

---

app/policies/dashboard_policy.rb
app/policies/equipment_policy.rb
app/policies/lab_policy.rb
app/policies/reservation_policy.rb
app/views/labs/show.html.erb

Separate views and ensure permissions are correct

separate lab and equipment views

---

db/seeds.rb

This PR addresses issue #102:
- Inserted all the information for the Innovaction Gym
- Created a Mock Mechatronics Lab

Modify Seeds.rb

---

app/views/lab_spaces/index.html.erb
app/views/labs/index.html.erb
app/views/labs/show.html.erb
app/views/shared/_nav.html.erb
db/seeds.rb

#110 
- Add "Laboratorios" and "Espacios" to the nav menu.
- Fix the buttons' links to each lab space
- Change some labels for proper ones
- Remove "HORARIO" from the Lab view
- Fix dev_entrypoint end of line sequence, becuase of a bug: https://forums.docker.com/t/standard-init-linux-go-175-exec-user-process-caused-no-such-file/20025/10

Change the lab and lab spaces views

---

Dockerfile
config/database.yml
docker-compose.yml

This PR:
1. Adds explicit bundler version environment variable value to Dockerfile
2. Refactors docker-compose.yml to use environment variables
3. Adds .env file with development environment variables
4. Adds "test" service as base app service to docker-compose from which "web" inherits now
5. Removes conflicting rails config/database.yml configuration to remove "Could not connect to Postgres server" errors.

Resolve docker and database configuration issues

---

.github/ISSUE_TEMPLATE/task.md

This PR:
+ Updates task template to meet requirements

Update task.md template

---

.github/ISSUE_TEMPLATE/task.md
.github/ISSUE_TEMPLATE/user-story.md

This PR:
+ Updates user-story.md template to meet requirements
+ Updates task.md template to meet requirements

Update Issue Templates

---

README.md

- The production app URL has been updated.
- The development app has been removed from the README.

Update Heroku app URL

---

app/views/lab_spaces/index.html.erb
app/views/labs/_lab_spaces_tables.html.erb

Add links to the labels of lab_space.name in:
- Lab space view
- Lab information view

Add links to the labels of lab_space.name

---

app/dashboards/lab_administration_dashboard.rb
app/policies/dashboard_policy.rb

This PR gives the ability to asssigne Lab Admins and Lab Spaces Admins to Laboratories and Lab Spaces.
- Change the administrate views and buttons that are shown in each dashboard.

Change the policies for the administration

---

app/assets/stylesheets/admin.css.scss
app/views/admin/application/_navigation.html.erb

- Added a different color when hovering a button
- Added 4 new navigation buttons (Profile, Labs, Labs Spaces and Equipments)
- Added 2 labels to help Admins differentiate the buttons

Admin Dashboard Navigation

---

app/assets/stylesheets/_base.scss
app/assets/stylesheets/_home.scss
app/views/home/landing.html.erb

This PR addresses issue #140 :
- Update styles of pills to differentiate capacities from materials.

Add different style by type to pills

---

app/policies/role_policy.rb

Remove the ability for a Lab Admin to upgrade another user to Lab_admin

Fix User policy

---

app/assets/stylesheets/_home.scss
app/views/home/landing.html.erb

This PR:
- Removes the outline highlight from fuzzy input fields in landing page

Remove fuzzy input outline on focus

---

app/controllers/home_controller.rb
app/mailers/makers_mailer.rb
app/models/reservation.rb
app/views/equipment/show.html.erb
app/views/home/profile.html.erb
app/views/makers_mailer/cancellation_email.html.erb
spec/factories/reservations.rb

Closes  #158 
- Added two new status (pending and rejected)
- Removed the cancel button on the rejected
- Show in calendar reservations that are pending, confirmed or blocked
- Free the space of reservations that were rejected
- Send a mail when a reservation is rejected

Fix reservations

---

app/dashboards/lab_space_dashboard.rb
config/environments/production.rb

* Fixes a bug related to outdated Uglifier configuration in asset precompilation
* Updates SendGrid password environment variable name

Update deployment configuration

---

app/models/lab.rb
app/models/lab_space.rb

* Makes the user field optional for user and lab space, this fixes the creation of these resources.

Make user optional in user and lab space

---

app/controllers/home_controller.rb
app/models/equipment.rb
app/views/home/landing.html.erb

* Creates method to sort the equipments by popularity (the amount of reservations it has had)

changes equipments cards on landing to sorted by popularity

---

app/views/shared/_equipment_landing.html.erb

* On the landing page, on the equipment cards, some links were broken because the IDs of lab and equipment were the other way around. This PR fixes that.

fix broken links

---

app/controllers/reservations_controller.rb
app/dashboards/reservation_dashboard.rb
app/helpers/reservations_helper.rb
app/views/equipment/show.html.erb
app/views/home/profile.html.erb
app/views/reservations/index.html.erb
db/migrate/20191122014703_add_help_needed_to_reservation.rb
db/schema.rb

* Adds attribute to Reservations (help_needed)
* This allows the user to select if they need help during their use of the reserved equipment.
* Adds button of help needed to form of new reservation in equipment show view

adds button if help is needed during equipment reservation

---

app/helpers/equipment_helper.rb
app/models/reservation.rb
app/views/equipment/show.html.erb

* Adds special (gray) coloring and "(pending)" label to calendar slots representing unconfirmed reservations
* Removes pending reservations from overlap considerations when booking a new reservation (i.e. two pending reservations can exist for an overlapping timeslot)
* Closes #173

Modify pending reservation behavior

---

app/assets/stylesheets/admin.css.scss
app/views/admin/equipment/_form.html.erb

* Updates the view of new equipment form; it is now divided into sections and more specific instructions were added.

Add new format to new equipment form

---

app/assets/javascripts/home.js
app/assets/stylesheets/admin.css.scss
app/controllers/home_controller.rb
app/helpers/home_helper.rb
app/views/admin/equipment/_form.html.erb
app/views/home/landing.html.erb

* Filters capabilities and materials if any of them is selected. Before this filtering was only done if only one of the pills was selected. All pills were rendered if both types had been selected.
* Clear input if a pill is selected.
* Updates the view of new equipment form; it is now divided into sections and more specific instructions were added.

Filter for any selected tag

---

app/views/equipment/show.html.erb

* Adds a single missing quote within an html tag to make the span containing the "cancelation" x mark valid html.

Fix reservation cancel from calendar

---

app/views/equipment/show.html.erb

* Check specific checkbox instead of all of them for the status field.
* Add label and color to blocked reservations in the calendar.

Fix creation of reservation

---

app/dashboards/reservation_dashboard.rb

Fix the creation of a reservation via admin dashboard, properly show the equipments lists and users.

Admin Dashboard Create Reservation

---

app/views/home/profile.html.erb
config/routes.rb

* Removes some links that broke the app when clicked.
* Removes reservation index route.

removes dangerous links

---

app/views/home/profile.html.erb
app/views/lab_spaces/_lab_space_equipment_tables.html.erb
config/routes.rb

* Adds link on cards of equipment on the spaces show page.

Link fixes

---

app/dashboards/reservation_dashboard.rb

Show reservation purpose on the admin dashboard and rearrange the order of how the attributes are shown.

Show reservation purpose and rearrange the order of the attributes

---

config/routes.rb

* Removes a route exception that broke the reservations index in Admin dashboard.

Remove reservations index route exclusion

---

app/controllers/admin/application_controller.rb

New order is now DESC on created_at

Made admin dashboards sort by most recent

---

app/views/equipment/show.html.erb

Changed the creation of new event to have them be like current evetns in both color and functionality

Color and Interactions of new Events

---

db/seeds.rb

Updated base seeds to reflect changes to the model.

TT015 Updated Seeds

---

app/mailers/application_mailer.rb
app/mailers/makers_mailer.rb
config/initializers/devise.rb

Change the setting of the app to use the email in the enviorments file instead of one that is already selected

Change Devise emails

---

spec/factories/capabilities.rb
spec/factories/capability.rb

Some changes where not commited when the branc TT017 was commited to master

Add Missing stuff from the merge

---

config/locales/en.yml
config/locales/es.yml

the error messages where optimized and placed on their respective yaml files

TT06 optimize error messages

---

config/locales/es.yml

Indendations where incorrect on the YML file

Fix to YML

---

app/views/shared/_calendar.js.erb

There was a nill value beign returned when the user was not signed_in

Removed Nil values

---

Deployment.md
app/models/reservation.rb

Put a condition so that lab spaces wont crash when they dont have a user assigned to them

Fix For LabSpaces
