app/controllers/equipment_controller.rb, app/models/available_hour.rb, app/models/equipment.rb
**User Story:** #16 
- Agregas el horario disponible al momento de crear/updatear un equipo
**Request received by controller:**
```{
"equipment":{
"name": "nombre del equipo",
"description": "gonna miss the rain",
"materials": "madera, tela",
"capabilities": "cort, imprime",
"available_hours": [
{
"start_time": "7:00",
"end_time": "14:00",
"day_of_week": 1
},
{
"start_time": "1:00",
"end_time": "3:00",
"day_of_week": 2
}
]
}
}
```
Notes:
-  Active Record assigns a default date to `start_time` & `end_time`
ex: `start_time: "2000-01-01 07:00:00"` `end_time: "2000-01-01 14:00:00"`
to format the time to Hour:Minutes as we want we can use `.to_formatted_s(:time)`
ex: `start_time.to_formatted_s(:time)` will return `"07:00"`
=> Add available hours to equipment

.gitignore, app/assets/stylesheets/_base.scss, app/assets/stylesheets/_equipment.scss, app/assets/stylesheets/_home.scss, app/assets/stylesheets/_labs.scss, app/controllers/application_controller.rb, app/controllers/home_controller.rb, app/views/equipment/index.html.erb, app/views/equipment/show.html.erb, app/views/home/landing.html.erb, app/views/labs/index.html.erb, app/views/shared/_search.html.erb, db/seeds.rb
This PR:
- Adds seeds for capabilities and materials and associates them to the generated seeded equipment
- Adds capabilities and materials to equipment **listing** (pills/tags)
- Adds capabilities and materials to equipment **show** (details view)
- Adds the corresponding lab space to the equipment details view
- Makes a few UI improvements to the equipment details view
- Adds dynamic filters for filtering on capability and materials on equipment listing / search results
- Adds dynamic behaviour for home search and enables the search
=> Add capabilities and materials to equipment views

app/models/lab_administration.rb, app/models/user.rb, app/policies/reservation_policy.rb
- Changes managed_* query to redo query with id's instead of returning array
- Authorizes new/create reservation without restriction
- Removes role restriction for lab administration.
=> Fix reservations scoping policy

app/controllers/admin/application_controller.rb, app/controllers/application_controller.rb, config/application.rb
- Change `Pundit::NotAuthorizedError` behavior: redirect to root instead of responding with `:forbidden` (403).
=> Redirect to root when attempting to access unauthorized action

app/assets/stylesheets/admin.css.scss, app/dashboards/equipment_dashboard.rb, app/views/admin/equipment/show.html.erb, app/views/equipment/show.html.erb, app/views/home/profile.html.erb
- Adds data for equipment view in `/admin/equipment`
- Only shows `blocked` and `confirmed` reservations for the external equipment page
=> Fix admin equipment view

app/controllers/admin/application_controller.rb
- Fixes bug when trying to create lab administration
- Overrides Administrate `read_param_value(data)` to include `PolymorphicWithUserField`
Related: #79
=> Fix lab administrations 'Unrecognised param data' error

app/controllers/equipment_controller.rb, app/models/capability.rb, app/models/equipment_capability.rb, app/models/equipment_material.rb, app/models/material.rb, app/policies/dashboard_policy.rb, app/views/equipment/show.html.erb, app/views/shared/_nav.html.erb, config/routes.rb, spec/policies/dashboard_policy_spec.rb
- agregar link para admins a navbar
- material/capability validation of `uniqueness`
- mover validación de borrar `orphaned` material/capability como `after_destroy` callback de las asociaciones, en lugar de realizarlo en los controladores
- cambiar orden de dashboard, equipment hasta arriba
- materiales/capability/available_hours no debería de aparecer en dashboard
- ficha técnica -> descripción técnica
Related: #79
=> Changes to dashboard and how materials/capabilities are destroyed

app/controllers/admin/equipment_controller.rb, app/controllers/equipment_controller.rb, app/models/equipment.rb, app/policies/user_policy.rb, app/views/admin/equipment/_collection.html.erb, app/views/admin/equipment/index.html.erb, app/views/equipment/show.html.erb, app/views/lab_spaces/show.html.erb, db/migrate/20190513160249_add_hidden_to_equipment.rb, db/schema.rb
- Added a `hidden` field for equipments instead of `destroy`.
- Added a `visible` scope to `equipment`, this returns equipment that is not hidden 🦆 
- Added date/time info in reservation modal
- Remove destroy user policy for all users
Hiding an equipment means users cannot see the equipment when navigating the main page.
=> Fix disable equipment

app/controllers/home_controller.rb, app/dashboards/equipment_dashboard.rb, app/dashboards/lab_administration_dashboard.rb, app/dashboards/reservation_dashboard.rb, app/dashboards/user_dashboard.rb, app/mailers/makers_mailer.rb, app/models/equipment.rb, app/models/reservation.rb, app/views/admin/equipment/show.html.erb, app/views/equipment/show.html.erb, app/views/makers_mailer/cancellation_email.html.erb, config/routes.rb
- Show only future reservations on profile
- Show upcoming reservations count on equipment dashboard
- Disable ability to change reservation status on equipment dashboard
- Hide 'blocked' status from reservation update in admin dashboard
- Only validate date if dates changed
- Send cancellation email if status changed to cancelled
=> Upcoming reservations changes

app/assets/stylesheets/_base.scss, app/views/admin/equipment/_form.html.erb, app/views/home/landing.html.erb, app/views/lab_spaces/show.html.erb
This PR:
- Enables diario and lu-vi in external and dashboard pages
- Fixes the card click event upon creation in external page when creating a new equipment
=> Enable add hours in external and internal page

app/controllers/labs_controller.rb, app/dashboards/lab_dashboard.rb, app/dashboards/lab_space_dashboard.rb, app/views/admin/equipment/_form.html.erb, app/views/admin/labs/_form.html.erb, app/views/labs/index.html.erb
This PR does the following:
* On the admin dashboard, fixed the "New Lab" and "New Lab Space" actions, by adding fields to select the Lab admin / lab space admin when creating the lab or lab space.
* For the "New lab" I modified Administrate's Lab Dashboard by adding user_id as attributes and form attributes. This permits the params when creating a new object, and if specified so (for New lab it is not specified) it automatically renders a field on the form.
* The same is done for New Lab Space, and in this case it is specified to render a field for the lab space admin automatically, so the form does not need to be modified.
=> fix creation of lab and labspaces

app/views/lab_spaces/show.html.erb
This PR:
+ Adds a restriction for the "add equipment" option
+  Closes #107
=> Remove the option for a normal user to add an equipment

app/assets/stylesheets/_labs.scss, app/assets/stylesheets/admin.css.scss, app/views/admin/equipment/show.html.erb, app/views/equipment/show.html.erb, app/views/home/landing.html.erb, app/views/lab_spaces/index.html.erb, app/views/lab_spaces/show.html.erb, app/views/labs/_lab_equipment_tables.html.erb, app/views/labs/_lab_spaces_tables.html.erb, app/views/labs/index.html.erb, app/views/labs/show.html.erb, app/views/shared/_nav.html.erb
#116 
This PR:
+ Changes the labels that were written in singular
+ Changes the labels from "Technical Description" to "Technical Specifications"
+ Removes the materials from the tag list in the lab view
+ Changes the fixed name to an email from the person in charge of the space
+ Changes the fixed schedule to the name of the space to which each team belongs
+ Eliminates the restriction that shows only the first 10 materials and capacities
=> Fix outdated and incorrect labels

config/environments/production.rb
This PR addresses issue #:
- The host used for the mailer has been replaced after the old Heroku account was lost and the app was deployed again.
=> Fix host for mailer

app/views/home/landing.html.erb
This PR addresses issue #124 :
- After selecting a pill in the capacity/material options and then removing it, it wasn't possible to select it again.
- This was because `.click(...)` was being used; it doesn't work on dynamically created elements.
- Instead of that, `.on('click', ...)` is now used.
=> Fix click on pills returned to the available options

app/dashboards/lab_space_dashboard.rb
* Fixes a bug in the Lab Spaces dashboard that crashed the app because the 'User' attribute was not listed in the Attribute Types hash in the lab spaces dashboard file.
=> Add User Attribute to Lab Spaces dashboard

app/controllers/admin/equipment_controller.rb, app/dashboards/lab_space_dashboard.rb, app/views/admin/equipment/show.html.erb, app/views/equipment/show.html.erb
* Implements a feature that blocks (grays out) the calendar space that does not correspond to the specific equipment's registered available hours (not including reserved slots).
* Closes #105
=> Fix Equipment Reservations Calendar in Admin Dashboard

app/controllers/admin/equipment_controller.rb, app/views/admin/equipment/_collection.html.erb
The alert which was being displayed on the prompt when attempting to hide/unhide equipment was removed and now the equipment just hides/unhides without further confirmation
=> D001 hidden button bug fix

app/views/lab_spaces/_lab_space_equipment_tables.html.erb, app/views/labs/_lab_equipment_tables.html.erb
Cards on Lab#show weren't clickable at all and on lab_spaces#show were just clickable inside margin and when not obstructed by other divs
=> Made Equipment cards on lab & lab_spaces clickable

app/mailers/makers_mailer.rb, app/models/reservation.rb, app/views/makers_mailer/status_email.html.erb, config/locales/en.yml, config/locales/es.yml
The mailer service has been changed to send a notification email whenever the status changed instead of only when it was rejected
=> TT012 Send Email on Status Change

app/models/reservation.rb, app/views/admin/equipment/show.html.erb, app/views/shared/_calendar.js.erb, config/locales/en.yml, config/locales/es.yml, db/migrate/20201028175102_remove_completed_status_from_reservation.rb, db/schema.rb
Status was never used in system, therefore no reason to change from "confirmed" to "completed".
* Added migration to change the status enum on reservations
* Made use-graphs look for confirmed reservations
=> Removed completed status

app/models/reservation.rb
Updated rules to only look at confirmed reservations to avoid blocking space on pending reservations, also to delete pending reservations when you make a blocked reservation that overlaps
=> Updated Reservation Rules

app/mailers/application_mailer.rb, app/mailers/makers_mailer.rb, app/models/reservation.rb, app/views/shared/_calendar.js.erb, config/initializers/devise.rb, spec/models/reservation_spec.rb
Admins can now now be drag events to other slots & resize their duration (within constraints)
* Added a constraint so user can no longer see past reservations on calendar
* Fixed bug on mailer specification
=> Added Reservation dragging & resizing

app/models/reservation.rb
Fixed blocked reservations behavior to correctly block time blocks according to mas usage_time and equipment_cooldown
=> Blocked Reservation Logic
